### ISSUE TITLE
mysql容器自动重启关闭循环

### ISSUE THREAD

**Issue by enboo** [yeszao/dnmp#84]
我这里使用docker-compose安装后，所有容器里只有mysql的会自动重启关闭重启关闭，
docker ps -a后的截图：
![image](https://user-images.githubusercontent.com/39607705/48700106-20eb3d00-ec26-11e8-9a6d-6606622800ad.png)
觉着可能是compose.yml文件或者evn我动到了哪里然后出了问题，
然后到stack overflow上查了这个问题，最好的答案为https://stackoverflow.com/questions/37471929/docker-container-keeps-on-restarting-again-on-again  
docker-compose文件里关于mysql的配置是：
![image](https://user-images.githubusercontent.com/39607705/48700278-9fe07580-ec26-11e8-835d-77f5f11b1ac2.png)
这里我尝试修改为：
\- MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"
前边加了个横杠-，冒号修改为等号=，然后docker-compose build，问题依旧，所以问问大家有没有遇到这个问题。

**Comment by Maskman24610** [comment]
先確認3306port是否有被其他程式佔用

**Comment by yeszao** [comment]
单独 docker-compose build mysql 有什么提示吗？

**Comment by enboo** [comment]
![image](https://user-images.githubusercontent.com/39607705/48811831-7a5c8480-ed6a-11e8-8fda-6b013af014bd.png)

昨天删除了mysql容器、卷、配置文件，然后重新build了，mysql容器现在一直处于created状态，build木有用，build mysql执行不了，因为mysql木有启动吧：
![image](https://user-images.githubusercontent.com/39607705/48811925-e212cf80-ed6a-11e8-9129-ad618a04c285.png)

现在我是直接pull了一个新的mysql5.6容器，木使用compose，也能用

**Comment by qq516249940** [comment]
liusuwanqing@ken:~/dnmp$ sudo docker-compose up   
Starting dnmp_mysql_1_f57b6a1eb2d0 ... 
dnmp_php56_1_18d27b9a2cc5 is up-to-date
dnmp_phpmyadmin_1_fd161800d20f is up-to-date
dnmp_php54_1_cbdddc1f3208 is up-to-date
dnmp_phpredisadmin_1_5e3bb136dc5b is up-to-date
dnmp_php72_1_e4b3f6db9460 is up-to-date
Starting dnmp_mysql_1_f57b6a1eb2d0 ... done
Starting dnmp_nginx_1_9fc11fa7effa ... done
Attaching to dnmp_php56_1_18d27b9a2cc5, dnmp_phpmyadmin_1_fd161800d20f, dnmp_php54_1_cbdddc1f3208, dnmp_phpredisadmin_1_5e3bb136dc5b, dnmp_php72_1_e4b3f6db9460, dnmp_redis_1_83817e8d6d2b, dnmp_mysql_1_f57b6a1eb2d0, dnmp_nginx_1_9fc11fa7effa
php56_1_18d27b9a2cc5 | [21-Nov-2018 07:10:46] NOTICE: fpm is running, pid 1
php56_1_18d27b9a2cc5 | [21-Nov-2018 07:10:46] NOTICE: ready to handle connections
php54_1_cbdddc1f3208 | [21-Nov-2018 07:10:42] NOTICE: fpm is running, pid 1
php54_1_cbdddc1f3208 | [21-Nov-2018 07:10:42] NOTICE: ready to handle connections
phpmyadmin_1_fd161800d20f | /usr/lib/python2.7/site-packages/supervisor/options.py:298: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
phpmyadmin_1_fd161800d20f |   'Supervisord is running as root and it is searching '
phpmyadmin_1_fd161800d20f | 2018-11-21 07:10:38,277 CRIT Supervisor running as root (no user in config file)
phpmyadmin_1_fd161800d20f | 2018-11-21 07:10:38,277 INFO Included extra file "/etc/supervisor.d/nginx.ini" during parsing
phpmyadmin_1_fd161800d20f | 2018-11-21 07:10:38,284 INFO Included extra file "/etc/supervisor.d/php.ini" during parsing
phpmyadmin_1_fd161800d20f | 2018-11-21 07:10:38,368 INFO RPC interface 'supervisor' initialized
phpmyadmin_1_fd161800d20f | 2018-11-21 07:10:38,368 CRIT Server 'unix_http_server' running without any HTTP authentication checking
phpmyadmin_1_fd161800d20f | 2018-11-21 07:10:38,369 INFO supervisord started with pid 1
phpmyadmin_1_fd161800d20f | 2018-11-21 07:10:39,371 INFO spawned: 'php-fpm' with pid 22
phpmyadmin_1_fd161800d20f | 2018-11-21 07:10:39,381 INFO spawned: 'nginx' with pid 23
phpmyadmin_1_fd161800d20f | 2018-11-21 07:10:40,439 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
phpmyadmin_1_fd161800d20f | 2018-11-21 07:10:40,439 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
phpredisadmin_1_5e3bb136dc5b | PHP 7.2.11 Development Server started at Wed Nov 21 07:10:39 2018
php72_1_e4b3f6db9460 | [21-Nov-2018 07:10:46] NOTICE: fpm is running, pid 1
php72_1_e4b3f6db9460 | [21-Nov-2018 07:10:46] NOTICE: ready to handle connections
redis_1_83817e8d6d2b | 1:C 21 Nov 2018 07:10:43.565 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1_83817e8d6d2b | 1:C 21 Nov 2018 07:10:43.565 # Redis version=5.0.1, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1_83817e8d6d2b | 1:C 21 Nov 2018 07:10:43.565 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1_83817e8d6d2b | 1:M 21 Nov 2018 07:10:43.569 * Running mode=standalone, port=6379.
redis_1_83817e8d6d2b | 1:M 21 Nov 2018 07:10:43.569 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1_83817e8d6d2b | 1:M 21 Nov 2018 07:10:43.569 # Server initialized
redis_1_83817e8d6d2b | 1:M 21 Nov 2018 07:10:43.569 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1_83817e8d6d2b | 1:M 21 Nov 2018 07:10:43.569 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1_83817e8d6d2b | 1:M 21 Nov 2018 07:10:43.569 * Ready to accept connections
mysql_1_f57b6a1eb2d0 | Initializing database
dnmp_mysql_1_f57b6a1eb2d0 exited with code 1
dnmp_mysql_1_f57b6a1eb2d0 exited with code 1
dnmp_mysql_1_f57b6a1eb2d0 exited with code 1
dnmp_mysql_1_f57b6a1eb2d0 exited with code 1
dnmp_mysql_1_f57b6a1eb2d0 exited with code 1
dnmp_mysql_1_f57b6a1eb2d0 exited with code 1
dnmp_mysql_1_f57b6a1eb2d0 exited with code 1
dnmp_mysql_1_f57b6a1eb2d0 exited with code 1
dnmp_mysql_1_f57b6a1eb2d0 exited with code 1
dnmp_mysql_1_f57b6a1eb2d0 exited with code 1
dnmp_mysql_1_f57b6a1eb2d0 exited with code 1
dnmp_mysql_1_f57b6a1eb2d0 exited with code 1
dnmp_mysql_1_f57b6a1eb2d0 exited with code 1
dnmp_mysql_1_f57b6a1eb2d0 exited with code 1
dnmp_mysql_1_f57b6a1eb2d0 exited with code 1
dnmp_mysql_1_f57b6a1eb2d0 exited with code 1
^CGracefully stopping... (press Ctrl+C again to force)
Stopping dnmp_redis_1_83817e8d6d2b         ... done
Stopping dnmp_nginx_1_9fc11fa7effa         ... done
Stopping dnmp_php72_1_e4b3f6db9460         ... done
Stopping dnmp_php56_1_18d27b9a2cc5         ... done
Stopping dnmp_phpredisadmin_1_5e3bb136dc5b ... done
Stopping dnmp_php54_1_cbdddc1f3208         ... done
Stopping dnmp_phpmyadmin_1_fd161800d20f    ... done
Stopping dnmp_mysql_1_f57b6a1eb2d0         ... done
liusuwanqing@ken:~/dnmp$ sudo lsof -i :3306
liusuwanqing@ken:~/dnmp$ docker logs dnmp_mysql_1_f57b6a1eb2d0
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/dnmp_mysql_1_f57b6a1eb2d0/logs?stderr=1&stdout=1&tail=all: dial unix /var/run/docker.sock: connect: permission denied
liusuwanqing@ken:~/dnmp$ sudo docker logs dnmp_mysql_1_f57b6a1eb2d0
Initializing database
liusuwanqing@ken:~/dnmp$ docker-compose build mysql
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
liusuwanqing@ken:~/dnmp$ sudo docker-compose build mysql
mysql uses an image, skipping
liusuwanqing@ken:~/dnmp$ 

> 用`docker-compose build mysql`
> 
> 这里用service名就可以，不需要`dump_`前缀和`_1`后缀

`liusuwanqing@ken:~/dnmp$ sudo docker-compose up   
Starting dnmp_mysql_1_f57b6a1eb2d0 ... 
dnmp_php56_1_18d27b9a2cc5 is up-to-date
dnmp_phpmyadmin_1_fd161800d20f is up-to-date
dnmp_php54_1_cbdddc1f3208 is up-to-date
dnmp_phpredisadmin_1_5e3bb136dc5b is up-to-date
dnmp_php72_1_e4b3f6db9460 is up-to-date
Starting dnmp_mysql_1_f57b6a1eb2d0 ... done
Starting dnmp_nginx_1_9fc11fa7effa ... done
Attaching to dnmp_php56_1_18d27b9a2cc5, dnmp_phpmyadmin_1_fd161800d20f, dnmp_php54_1_cbdddc1f3208, dnmp_phpredisadmin_1_5e3bb136dc5b, dnmp_php72_1_e4b3f6db9460, dnmp_redis_1_83817e8d6d2b, dnmp_mysql_1_f57b6a1eb2d0, dnmp_nginx_1_9fc11fa7effa
php56_1_18d27b9a2cc5 | [21-Nov-2018 07:10:46] NOTICE: fpm is running, pid 1
php56_1_18d27b9a2cc5 | [21-Nov-2018 07:10:46] NOTICE: ready to handle connections
php54_1_cbdddc1f3208 | [21-Nov-2018 07:10:42] NOTICE: fpm is running, pid 1
php54_1_cbdddc1f3208 | [21-Nov-2018 07:10:42] NOTICE: ready to handle connections
phpmyadmin_1_fd161800d20f | /usr/lib/python2.7/site-packages/supervisor/options.py:298: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
phpmyadmin_1_fd161800d20f |   'Supervisord is running as root and it is searching '
phpmyadmin_1_fd161800d20f | 2018-11-21 07:10:38,277 CRIT Supervisor running as root (no user in config file)
phpmyadmin_1_fd161800d20f | 2018-11-21 07:10:38,277 INFO Included extra file "/etc/supervisor.d/nginx.ini" during parsing
phpmyadmin_1_fd161800d20f | 2018-11-21 07:10:38,284 INFO Included extra file "/etc/supervisor.d/php.ini" during parsing
phpmyadmin_1_fd161800d20f | 2018-11-21 07:10:38,368 INFO RPC interface 'supervisor' initialized
phpmyadmin_1_fd161800d20f | 2018-11-21 07:10:38,368 CRIT Server 'unix_http_server' running without any HTTP authentication checking
phpmyadmin_1_fd161800d20f | 2018-11-21 07:10:38,369 INFO supervisord started with pid 1
phpmyadmin_1_fd161800d20f | 2018-11-21 07:10:39,371 INFO spawned: 'php-fpm' with pid 22
phpmyadmin_1_fd161800d20f | 2018-11-21 07:10:39,381 INFO spawned: 'nginx' with pid 23
phpmyadmin_1_fd161800d20f | 2018-11-21 07:10:40,439 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
phpmyadmin_1_fd161800d20f | 2018-11-21 07:10:40,439 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
phpredisadmin_1_5e3bb136dc5b | PHP 7.2.11 Development Server started at Wed Nov 21 07:10:39 2018
php72_1_e4b3f6db9460 | [21-Nov-2018 07:10:46] NOTICE: fpm is running, pid 1
php72_1_e4b3f6db9460 | [21-Nov-2018 07:10:46] NOTICE: ready to handle connections
redis_1_83817e8d6d2b | 1:C 21 Nov 2018 07:10:43.565 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1_83817e8d6d2b | 1:C 21 Nov 2018 07:10:43.565 # Redis version=5.0.1, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1_83817e8d6d2b | 1:C 21 Nov 2018 07:10:43.565 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1_83817e8d6d2b | 1:M 21 Nov 2018 07:10:43.569 * Running mode=standalone, port=6379.
redis_1_83817e8d6d2b | 1:M 21 Nov 2018 07:10:43.569 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1_83817e8d6d2b | 1:M 21 Nov 2018 07:10:43.569 # Server initialized
redis_1_83817e8d6d2b | 1:M 21 Nov 2018 07:10:43.569 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1_83817e8d6d2b | 1:M 21 Nov 2018 07:10:43.569 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1_83817e8d6d2b | 1:M 21 Nov 2018 07:10:43.569 * Ready to accept connections
mysql_1_f57b6a1eb2d0 | Initializing database
dnmp_mysql_1_f57b6a1eb2d0 exited with code 1
dnmp_mysql_1_f57b6a1eb2d0 exited with code 1
dnmp_mysql_1_f57b6a1eb2d0 exited with code 1
dnmp_mysql_1_f57b6a1eb2d0 exited with code 1
dnmp_mysql_1_f57b6a1eb2d0 exited with code 1
dnmp_mysql_1_f57b6a1eb2d0 exited with code 1
dnmp_mysql_1_f57b6a1eb2d0 exited with code 1
dnmp_mysql_1_f57b6a1eb2d0 exited with code 1
dnmp_mysql_1_f57b6a1eb2d0 exited with code 1
dnmp_mysql_1_f57b6a1eb2d0 exited with code 1
dnmp_mysql_1_f57b6a1eb2d0 exited with code 1
dnmp_mysql_1_f57b6a1eb2d0 exited with code 1
dnmp_mysql_1_f57b6a1eb2d0 exited with code 1
dnmp_mysql_1_f57b6a1eb2d0 exited with code 1
dnmp_mysql_1_f57b6a1eb2d0 exited with code 1
dnmp_mysql_1_f57b6a1eb2d0 exited with code 1
^CGracefully stopping... (press Ctrl+C again to force)
Stopping dnmp_redis_1_83817e8d6d2b         ... done
Stopping dnmp_nginx_1_9fc11fa7effa         ... done
Stopping dnmp_php72_1_e4b3f6db9460         ... done
Stopping dnmp_php56_1_18d27b9a2cc5         ... done
Stopping dnmp_phpredisadmin_1_5e3bb136dc5b ... done
Stopping dnmp_php54_1_cbdddc1f3208         ... done
Stopping dnmp_phpmyadmin_1_fd161800d20f    ... done
Stopping dnmp_mysql_1_f57b6a1eb2d0         ... done
liusuwanqing@ken:~/dnmp$ sudo lsof -i :3306

liusuwanqing@ken:~/dnmp$ sudo docker logs dnmp_mysql_1_f57b6a1eb2d0
Initializing database

liusuwanqing@ken:~/dnmp$ sudo docker-compose build mysql
mysql uses an image, skipping`

和楼上基本相同····
但是运行docker-compose build mysql 提示mysql uses an image, skipping

**Comment by Yven** [comment]
![image](https://user-images.githubusercontent.com/10890849/48827193-80248b00-eda7-11e8-8ee2-d735de18a601.png)
我这边一直初始化数据库，看到在mysql/mysql.error.log里有一行error是
```
2018-11-21T07:56:09.608989Z 0 [ERROR] [MY-010361] [Server] Fatal error: Illegal or unknown default time zone 'Asia/Shanghai'
```
然后我把conf/my.cnf里的`default-time-zone`那行删了再重启就可以了

**Comment by yeszao** [comment]
已改为 '+8:00' 格式
